backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: team
    label: Team Member
    folder: static/team
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Name
        widget: string
      - name: employeeTitle
        label: Title
        widget: string
        required: false
      - name: date
        label: Date
        widget: date
      - name: path
        label: Path
        widget: string
      - name: image
        label: Image
        widget: image
      - name: bio
        label: Bio
        widget: markdown
      - name: twitter
        label: Twitter Handle
        widget: string
        required: false
      - name: Quora
        label: Quora Username
        widget: string
        required: false
