backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: src/team
    label: Team Member
    folder: team
    create: true
    slug: "{{slug}}"
    fields:
      - name: name
        label: Name
        widget: string
      - name: title
        label: Title
        widget: string
      - name: bio
        label: Bio
        widget: markdown
      - name: twitter
        label: Twitter Handle
        widget: string
      - name: Quora
        label: Quora Username
        widget: string
  - name: src/blog
    label: Blog
    folder: blog
    create: true
    slug: "{{year}}-{{month}}-{{slug}}" # this will be the file name
    fields:
      - name: title
        label: Title
        widget: string
      - name: metaTitle
        label: Meta Title
        widget: string
        pattern: [".{0,43}", "Must not be more than 43 characters"]
      - name: metaDescription
        label: Meta Description
        widget: text
        pattern: [".{0,300}", "Must not be more than 300 characters"]
      - name: date
        label: Publish Date
        widget: datetime
      - name: body
        label: Body
        widget: markdown
      - name: tags
        label: Tags
        widget: list
        allow_add: true
      - name: author
        label: Post Author
        widget: relation
        collection: team
        searchFields: ["name"]
        valueField: name
        displayFields: ["name", "title"]
